{
 "title": "GreenIT-Analysis",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "scenarioName",
    "label": "Scenario",
    "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n    bucket: v.defaultBucket,\r\n    tag: \"scenarioName\",\r\n    start: -1y\r\n)\r\n"
   },
   {
    "name": "actionName",
    "label": "Action",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: v.defaultBucket,\n    tag: \"actionName\",\n    predicate: (r) => r._measurement == \"eco_index\" and r.scenarioName == ${scenarioName:doublequote},\n    start: -1y\n)\n"
   }
  ]
 },
 "panels": [
  { "title": "Last analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Analysis date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"date\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "Ecoindex",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"ecoindex\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "GES (gC02eq)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"ges\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"nbRequest\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "Response size (Ko)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"responsesSize\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "Water (cl)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"water\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "DOM size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"domSize\")\r\n    |> last()"
    }
   ]
  },
  {
   "title": "Response size uncompressed (Ko)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"responsesSizeUncompress\")\r\n    |> last()"
    }
   ]
  },
  { "title": "Evolution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Eco Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eco_index",
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: $__from/1000, stop: $__to/1000)\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"ecoindex\")",
     "select": [
      [
       { "params": [ "EcoIndex" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"nbRequest\")"
    }
   ]
  },
  {
   "title": "Dom size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"domSize\")"
    }
   ]
  },
  {
   "title": "Response size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: $__from/1000, stop: $__to/1000)\r\n    |> filter(fn: (r) => r._measurement == \"eco_index\" and r.scenarioName == \"${scenarioName}\" and r.actionName == \"${actionName}\" and r._field == \"responsesSize\")"
    }
   ]
  }
 ]
}